spring:
  datasource:
    url: jdbc:mysql://47.101.193.185:3306/WMSLAOYANG?characterEncoding=UTF-8&nullCatalogMeansCurrent=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
    username: root
    password: 433193da9f88
    driver-class-name: com.mysql.cj.jdbc.Driver
  messages:
    fallback-to-system-locale: false

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

pagehelper:
  reasonable: true
  offsetAsPageNum: true
  pageSizeZero: true
  rowBoundsWithCount: true


logging:
  level:
    com:
      connext:
        wms:
          dao: debug
